added code
Szpytowski/Cinema-ticket pull request #1
Opened 2024-08-27 02:24 UTC by Szpytowski

Added my code, I struggled with margin and padding on this one.

2024-08-27 15:09 UTC, Solnick requested changes
![image](https://github.com/user-attachments/assets/6eda7e77-d0b7-43cc-a5a6-d9c7a45c30c0)
There are some obvious differences to fix, for example the font.

2024-08-27 15:10 UTC, Solnick requested changes
![image](https://github.com/user-attachments/assets/44464eeb-69aa-4612-9a5d-329e724e59ec)
Also make sure to fulfill all the requirements

2024-08-27 15:19 UTC, Solnick requested changes

2024-08-27 15:19 UTC, Solnick commented on css/style.css
> +body{
```suggestion
body {
```
Remember about space after the selector.

2024-08-27 15:19 UTC, Solnick commented on css/style.css
> +    box-sizing: border-box;
use box-sizing globally, for example using `body` or `*` selector

2024-08-27 15:19 UTC, Solnick commented on css/style.css
> +    font-family: Arial, sans-serif;
Please find the correct font in figma 
![image](https://github.com/user-attachments/assets/27aad601-d9eb-42e7-b808-c32b449017f6)

2024-08-27 15:19 UTC, Solnick commented on css/style.css
> +    width: 134.26px;
don't use decimal point in pixels

2024-08-27 15:19 UTC, Solnick commented on css/style.css
> +    transform: rotate(1.62deg);
why such a value?

2024-08-27 15:19 UTC, Solnick commented on css/style.css
> +    font-family: 'Roboto';
remember to use the fallback font
```
    font-family: 'Roboto', sans-serif;
```

2024-08-27 15:19 UTC, Solnick commented on css/style.css
> +    display: flex;
Do you really want to add those styles for every h2 on the web page? Please us the class selector to be more specific. Using the tag selectors is rarely needed and should be used only when you really want to globally change all the elements in the webpage.

2024-08-27 15:19 UTC, Solnick commented on css/style.css
> +
When programming leave only one blank line at the end of any file

2024-08-27 15:19 UTC, Solnick commented on index.html
> +            <p>GATE: 03 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; SEAT: B43</p>
Please don't use the space sign for positioning, instead use CSS rules, for example flexbox

2024-09-03 12:00 UTC, Solnick approved these changes

2024-09-03 12:00 UTC, Solnick commented on css/style.css
> +    transform:  rotate(5deg);
```suggestion
    transform: rotate(5deg);
```
One space is enough

2024-09-03 12:00 UTC, Solnick commented on css/style.css
> +    opacity: 1;
That's a good solution. I just want to let you know that you could've hide the little popcorn images under the popcorn box by using `transform: translate(x, y);` then the transition would make it pop out of the popcorn box. You can try it if you wish.

2024-09-03 13:59 UTC, Szpytowski commented on css/style.css
> +    opacity: 1;
done

2024-09-03 13:59 UTC, Szpytowski commented on css/style.css
> +    transform:  rotate(5deg);
done

2024-09-03 19:00 UTC, merged